db:
    image: mysql:5.5
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: project
        MYSQL_USER: root
        MYSQL_PASSWORD: root
php:
    image: claudioflagbit/docker-php
    expose:
        - 9000:9000
    links:
        - db
    volumes:
        - src:/var/www/html
    tty: true
apache:
    image: claudioflagbit/docker-apache
    ports:
        - 80:80
        - 443:443
    links:
        - php
    volumes_from:
        - php
    domainname: project.dev